"""
Central PDF Tools error catalog.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "PDFT-1000"
    UNKNOWN_FORM_FIELD = "PDFT-1001"
    AUTHENTICATION_FAILED = "PDFT-1100"
    INVALID_API_KEY = "PDFT-1101"
    PDF_PROCESSING_ERROR = "PDFT-1200"
    INVALID_PDF = "PDFT-1201"
    FILE_UPLOAD_ERROR = "PDFT-1300"
    CONFIGURATION_ERROR = "PDFT-1400"
    INTERNAL_ERROR = "PDFT-1500"
